#session_config:
#    n_inter_threads: 2
#    n_intra_threads: 32

data_config:
    train_file: /global/cscratch1/sd/sfarrell/atlas-rpv-images/train.h5
    valid_file: /global/cscratch1/sd/sfarrell/atlas-rpv-images/val.h5
    test_file: /global/cscratch1/sd/sfarrell/atlas-rpv-images/test.h5
    n_train: 65536 #412416
    n_valid: 32768
    n_test: 1024

model_config:
    conv_sizes: [16, 32, 64]
    dense_sizes: [128]
    optimizer: Adam
    learning_rate: 0.001
    dropout: 0.2

training_config:
    batch_size: 128
    n_epochs: 4

output_dir: $SCRATCH/hep-cnn-pytorch
